configure:
    cmake -B build -GNinja -DCMAKE_CXX_COMPILER=clang++ -DFEATURE_REPL=ON

build: configure
    cmake --build build

run: build
    ./build/riscv-emu ./probe/bin-asm -v

c: build
    ./build/riscv-emu ./probe/bin-c -v

repl: build
    ./build/riscv-emu :repl

test: build
    ./build/tests
