configure:
    cmake -B build -GNinja -DCMAKE_CXX_COMPILER=clang++ -DFEATURE_REPL=ON

build: configure
    cmake --build build

gdb: build
    ./build/riscv-emu ./probe/bin-asm --gdb -v

connect:
    gdb -ex "set debug remote 1" -ex "file ./probe/bin-asm" -ex "target remote /tmp/riscv-emu/gdbserver.sock"

run: build
    ./build/riscv-emu ./probe/bin-asm -v

c: build
    ./build/riscv-emu ./probe/bin-c -v

repl: build
    ./build/riscv-emu :repl

test: build
    ./build/tests
